import type { Metadata } from "next";
import { Encode_Sans_Expanded } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import  { Toaster } from 'react-hot-toast';
import NextauthProviders from "@/Providers/Components/nextauth.providers";
import Providers from "@/Providers/Components/ReactproviderQuery";
const encode = Encode_Sans_Expanded({
  subsets: ["latin"],
weight:['300','400']
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${encode.className}  antialiased`}
      >
        <Providers>

        <div className=" flex flex-col justify-between  min-h-screen">
          <NextauthProviders>

<Navbar></Navbar>
        <div className=" container">

        {children}
        </div>
              <Toaster />

        <Footer></Footer>
          </NextauthProviders>
        </div>
        </Providers>
      </body>
    </html>
  );
}
